mode: prod
prod:
  - botname: Slow VPN
    username: SlowVPNBOT
    subscription-domain: 'https://sub.slow-service.com'
    admin: 1211590718
    token: 
      6518933256:AAFK2pySUi5y5kX5D6-uM5GRZga3YaCE7WY
    database:
      "mongodb+srv://thefurbykins:kmbG4gPY5nbWbXXb@slowvpn.skaifir.mongodb.net/?retryWrites=true&w=majority"
    cryptomus-payment-key:
      'if7oiiAZyTGUk5BpC33rLiUCgxx887qD2Eb2pnWXjubj7ATfkX74WS4Cqe8xvHujNQ9qMYgMcCbbr45FHGIHnO5mOoyVbXpuCCy8KKzlRoHgiyuFMjqnKH3xbJyCCQZD'
    cryptomus-merchant-uuid:
      'f3225265-c19f-4ea5-9d1c-4598c10aed58'
    support-id:
      ''
    channel-id:
      'SlowService'
    punch-line:
      'با اسلو، اینترنت هم وقت برای یک فنجان چای داره!'
    test-subscription-traffic: #GB is the main identifier
      1
    test-subscription-time: #Seconds
      86400
    traffic-plans:
      - traffic: 50
        price: 50000
      - traffic: 75
        price: 75000
      - traffic: 100
        price: 100000
    irr-portal:
      - link: 'https://api.fastswaptrx.com/v1/creatPayment'
        key: '6126561376:1f2fd85c8b8be76f2e492c2c5c7be88a'
    force-channels:
      - id: -1001860158304
        link: 'https://t.me/+hjcbgWl3jyw2Yzk0'

