mode: prod
prod:
  - botname: VingPN #Bot Name
    username: VingPNBot #Bot Username
    subscription-domain: 'https://sub.vingpn.com' #Subscription Doman (Lazem nist hatman set bashe)
    admin: 5818413947 # Admin ID
    token:
      BOT_TOKEN
    database:
      "mongodb://localhost:27017/" #Mongodb
    cryptomus-payment-key:
      ''
    cryptomus-merchant-uuid:
      ''
    support-id:
      'VingSupport'
    channel-id:
      'VingPN'
    punch-line:
      'ایمن، ناشناس و متصل به دنیا بمانید'
    test-subscription-traffic: #GB is the main identifier
      3
    test-subscription-time: #Seconds
      604800
    traffic-plans: #پایه و اولیه، اضافه هم میشه زد داخل پنل مدیریت
      - traffic: 50
        price: 80000
      - traffic: 100
        price: 140000
      - traffic: 200
        price: 220000
    irr-portal: #ترونادو آیدیشو ازم بگیرید
      - link: 'https://api.fastswaptrx.com/v1/creatPayment'
        key: 'API Key'
    force-channels:
      - id: -1001745756265
        link: 'https://t.me/+WjDmPa0ePss2MmE0'
